### ISSUE TITLE
Registration about mask

### ISSUE THREAD

**Issue by nh13871101238** [stnava/BasicBrainMapping#3]
Dear author:
         First, thanks for your "BasicBrainMapping" example about mask to restrict the registration in the mask region.But I am confused about the later registration in the "bbs.sh" script, there are two registrations in this script:
1. One is the registration of "T_template2.nii.gz" and "IXI594-Guys-1089-T1.nii.gz" with mask "T_templateExtractionMask.nii.gz". 
2. Another is the registration of "T1_lesioned.nii.gz" and "T_template2.nii.gz" with mask "neg_lesion.nii.gz"

Here are my doubt:
1. It seems the second registration's mask is very different with the first registration's mask, is even not the binary files, really strange me.
2. I can not understand the purpose of the sencond registration, could you explain to me ?
3. Could the mask registration to restrict the registration in a very small region, because i have a attemp  when the mask is small, ants report errors with "Too many samples map outside moving image buffer. There are only 13 valid points out of 3912 total points"
4. Do you have more examples about mask registration?

Looking forward to your reply

Thanks

hni

**Comment by stnava** [comment]
my comments on your questions:
1.  i would not assume any connection between the two examples.  this is simulation data that is provided for illustrative purposes.
2.  the 2nd registration example is what one might do to register brains when a lesion is present.  see, for example, http://onlinelibrary.wiley.com/doi/10.1002/hbm.23110/abstract
3. note that the mask should define what is included, not what is excluded.  you may be better off cropping images, if you want to restrict registration.  or using a metric other than MI.  there is discussion elsewhere on the ants site.
4. there should be more examples around but we do not have a global index of these.  you can look at the Insight ToolKit source code if you care about the implementation details.

**Comment by nh13871101238** [comment]
thank for your reply.
